config/routes.rb
Rails.application.routes.draw do
  resources :orders, only: [:new, :create]
  root "events#index"
  get 'static_pages/index'
  get 'static_pages/secret'
  devise_for :users
  resources :events
  resources :attendances
  
  resources :users, only: [:edit, :show, :update] do
    resources :avatars, only: [:create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :attendances
  has_many :users, through: :attendances
  
begin 
  validates :duration, presence: true, format: { with: /\A\d+(?:\.\d{2})?\z/ }, numericality: { greater_than: 0}
  validates :title, length: {minimum: 5, maximum: 140}
  validates :description, length: {minimum: 20, maximum: 1000}
  validates :price, presence: true, format: { with: /\A\d+(?:\.\d{2})?\z/ }, numericality: { greater_than: 0, less_than: 1000 }
  validates :location, presence: true
  validate :start_date

  def not_past_date
    if self.date < Date.today
      errors.add(:start_date, 'not in past')
    end
  end
end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  after_create :welcome_send

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

  def password_reset_send
    UserMailer.reset_password_instructions(self).deliver_now
  end 
  
  has_many :events, through: :attendances
  has_many :attendances
  
  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

   
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
  end

  def update
  end

  def destroy
  end
end

app/controllers/avatars_controller.rb
class AvatarsController < ApplicationController
    
    def create
        @user = User.find(params[:user_id])
        @user.avatar.attach(params[:avatar])
        redirect_to(user_path(@user))
    end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  #before_action :authenticate_user!
  before_action :set_event, only: %i[ show edit update destroy ]
  def index
  @event = Event.all
  end

  def new
    @event = Event.new
  end

  def create
  @event = Event.new(event_params)
    if user_signed_in? == false
      redirect_to root_path, warning: "you must be registered and login to create an event!"
    end
    
    if @event.save == true
      redirect_to root_path, notice: "The event has been created"
    else
      redirect_to new_event_path, alert: "All fields are mandatory"
    end
    
  end

  def edit
    @event = Event.find(params[:id])
  end

  def show
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if user_signed_in? == false || (current_user.id < @event.user_id || current_user.id > @event.user_id)
      redirect_to root_path, message: "you must be registered and login to create an event!" 
    else 
      @event.update(event_params)
      redirect_to events_path
    end 
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_path
  end

  private
    def event_params
      params.require(:event).permit(:start_date, :duration, :title, :description, :price, :location).merge(user_id: current_user.id)
    end
    
    def set_event
      @event = Event.find(params[:id])
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
    @user = current_user
    @event = Event.first
    @amount = @event.price
    @stripe_amount = (@amount * 100).to_i
  end

  def create
    # Before the rescue, at the beginning of the method
    @user = current_user
    @event = Event.first
    @amount = @event.price
    @stripe_amount = (@amount * 100).to_i

    begin

    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken], 
    })

    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @stripe_amount,
      description: "Achat d'un produit",
      currency: 'eur',
    })

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_order_path
    end
    # After the rescue, if the payment succeeded
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!, only: [:secret]
  def index
  end

  def secret
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


    def edit
        @user = User.find(current_user.id)   

    end

    def show 
        @user = User.find(current_user.id)
    end

    def update
        @user = User.find(current_user.id)
        @user.update(user_params)
        redirect_to 
    end

    private 
    def user_params
        params.require(:user).permit(:fisrt_name, :last_name, :description)
    end 

end

app/helpers/application_helper.rb
module ApplicationHelper
    def bootstrap_class_for_flash(type)
        case type
          when 'success' then "alert-info"
          when 'notice' then "alert-success"
          when 'alert' then "alert-danger"
          when 'error' then "alert-warning"
        end
      end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/attendances/create.html.erb
<h1>Attendances#create</h1>
<p>Find me in app/views/attendances/create.html.erb</p>

app/views/attendances/destroy.html.erb
<h1>Attendances#destroy</h1>
<p>Find me in app/views/attendances/destroy.html.erb</p>

app/views/attendances/edit.html.erb
<h1>Attendances#edit</h1>
<p>Find me in app/views/attendances/edit.html.erb</p>

app/views/attendances/index.html.erb
<h1>Attendances#index</h1>
<p>Find me in app/views/attendances/index.html.erb</p>

app/views/attendances/show.html.erb
<h1>Attendances#show</h1>
<p>Find me in app/views/attendances/show.html.erb</p>

app/views/attendances/update.html.erb
<h1>Attendances#update</h1>
<p>Find me in app/views/attendances/update.html.erb</p>

app/views/events/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
    <br><br><br>
       <%= form_with model: @event, local: true do |form| %>
      <h1 class="h3 mb-3 font-weight-normal text-center">Modifie ton évènement !</h1>
      <% if @event.errors.any? %>
                  <div id="error_explanation">
                    <h2>
                      <%= pluralize(@event.errors.count, "error") %> prohibited
                      this event from being saved:
                    </h2>
                    <ul>
                      <% @event.errors.full_messages.each do |msg| %>
                        <li><%= msg %></li>
                      <% end %>
                    </ul>
                  </div>
                <% end %>
  <div class="form-group">
    <%= form.label :title, "Title" %><br>
    <%= form.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :description %><br>
    <%= form.text_field :description, class: "form-control"  %>
  </div>
   <div class="form-group">
    <%= form.label :price %><br>
    <%= form.text_field :price, class: "form-control"  %>
  </div>
   <div class="form-group">
    <%= form.label :duration %><br>
    <%= form.text_field :duration, class: "form-control"  %>
  </div>
   <div class="form-group">
    <%= form.label :location %><br>
    <%= form.text_field :location, class: "form-control"  %>
  </div>
  <div class="form-group">
    <%= form.label :start_date %><br>
    <%= form.text_field :start_date, class: "form-control" %>
  </div>
  <div class="actions mt-5">
    <%= form.submit"Confirm modifications", class: "btn btn-lg btn-primary btn-block"%>
  </div>
    <% end %>
    <%= link_to 'Revenir au Evenements', static_pages_index_path %>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="eventbrite.css" rel="stylesheet">
        <link href="bootstrap.min.css" rel="stylesheet">

        
    </head>
    <body>

      <h1 style="text-align: center; margin-top: 20px;">Events</h1>
       <div class="row justify-content-center" style="margin: 30px;">
       <% @event.each do |event| %>
        
            
              <div class="card text-white bg-primary col-3" style="margin: 20px;">
                <div class="card-header"><%= event.title %></div>
                <div class="card-body">
                  <h4 class="card-title"><%= event.title %></h4>
                  <p class="card-text"><%= event.description %></p>
                  <p class="card-text"><small class="text-muted"> Start in <%= event.start_date %></small></p>
                </div>
              </div>
          

      <% end %>
      </div>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    </body>
</html>

app/views/events/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
    <br><br><br>
      <%= form_with scope: :event, url: events_path, local: true do |form| %>
      <h1 class="h3 mb-3 font-weight-normal text-center">Crée ton évent! Yeah!</h1>
  <div class="form-group">
    <%= form.label :title, "Title" %><br>
    <%= form.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :description %><br>
    <%= form.text_area :description, class: "form-control"  %>
    <p style="font-size: x-small;  text-align: right;">20-150</p>
  </div>
   <div class="form-group">
    <%= form.label :price %><br>
    <%= form.text_field :price, class: "form-control"  %>
  </div>
   <div class="form-group">
    <%= form.label :duration %><br>
    <%= form.text_field :duration, class: "form-control"  %>
  </div>
   <div class="form-group">
    <%= form.label :location %><br>
    <%= form.text_field :location, class: "form-control"  %>
  </div>
  <div class="form-group">
    <%= form.label :start_date %><br>
    <%= form.text_field :start_date, class: "form-control" %>
    <p style="font-size: x-small; text-align: right;">year-month-day</p>
  </div>
  <div class="actions mt-5">
    <%= form.submit"Créer", class: "btn btn-lg btn-primary btn-block"%>
  </div>
    <% end %>
    <%= link_to 'Revenir au Evenements', static_pages_index_path %>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<div class="col">
          <div class="card shadow-sm">
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="https://media.discordapp.net/attachments/805846981351964692/811274555053703178/Capture_decran_2021-02-16_a_17.35.00.png" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>

            <div class="card-body">
              <p class="card-text">
              <%= @event.description%>
              </p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <% if user_signed_in? == false || (current_user.id < @event.user_id || current_user.id > @event.user_id)  %>
                  <button type="button" class="btn btn-sm btn-outline-secondary">
                  <%=link_to"Buy ticket for #{@event.price.to_i}€", new_order_path%></button>
                  <%else%>
                  <button type="button" class="btn btn-sm btn-outline-secondary">Attendees</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary">
                  <%=link_to"Edit", edit_event_path%></button>
                  <button type="button" class="btn btn-sm btn-outline-secondary">
                  <%= link_to "delete", {:controller => :events,
                    :action => 'destroy', :id => @event.id }, :method => :delete %></button>
                  <button type="button" class="btn btn-sm btn-outline-secondary">
                  <%=link_to"Attendences", attendances_path%></button>
                  <%end%>

                </div>
                <small class="text-muted">Created by <%= @event.user.email%></small>
              </div>
            </div>
          </div>
        </div>

app/views/layouts/_flash.html.erb
<% flash.each do |type, msg|%>
<div class="alert <%= bootstrap_class_for_flash(type) %> alert-dismissable fade show" role="alert">
  <%= msg %>
</div>
<% end %>

app/views/layouts/_footer.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="style.css" rel="stylesheet">
    <link href="styles.css" rel="stylesheet">
    <title>footer</title>
</head>

<body>
    
<footer class="footer">
    <h2 style="color: white; text-align: center; margin-top: 30px;">footer</h2>
</footer>
</body>

</html>

app/views/layouts/_navbar.html.erb
   <nav class="navbar navbar-expand-md navbar-dark bg-primary">
        <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="#">Parcourir les évenements</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Aide</a>
                </li>
            </ul>
        </div>
        <div class="mx-auto order-0">
            <a class="navbar-brand mx-auto" href="/">Eventbrite</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".dual-collapse2">
              <span class="navbar-toggler-icon"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
            
            <% if user_signed_in? %>
            <ul class="navbar-nav ml-auto">
                <li  class="nav-item">
                    <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-link" %>
                    
                </li>

                <li  class="nav-item">                    
                    <%= link_to "My profil", static_pages_secret_path, class: "nav-link" %>
                </li>

                <li  class="nav-item" > 
                    <%= link_to "Create event", new_event_path, class: "nav-link" %>
                </li>
            </ul>
            <% else %>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
                </li>
                <li class="nav-item">                    
                    <%= link_to "Log in", user_session_path, class: "nav-link" %>
                </li>
            </ul>
            <% end %> 
        </div>
    </nav>

                   
            

            
            
          
            

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>

  <link href="/your-path-to-fontawesome/css/fontawesome.css" rel="stylesheet">
  <link href="/your-path-to-fontawesome/css/brands.css" rel="stylesheet">
  <link href="/your-path-to-fontawesome/css/solid.css" rel="stylesheet">

   <title>Eventbrite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar"%>
    <%= render "layouts/flash"%>
    <%= yield %>
    <%= render "layouts/footer"%>
  </body>
</html>

app/views/orders/create.html.erb
<h1>Votre paiement est confirmé.</h1>

<h2>Merci <%= @user.email %> pour votre achat de <strong><%= 
@amount %> €</strong> !</h2>

<p>Un email vous a été envoyé à <%= @user.email %> avec le 
récapitulatif de votre commande.</p>
<%= link_to "Revenir à la page d'accueil", events_path%>

app/views/orders/new.html.erb
<h1>Bienvenue sur ma page de paiement, <%= @user.email %> !</h1>
<p>Vous avez choisi le produit <%= @event.title %>.</p><%= form_tag orders_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>    <label class="amount">
      <span>Son prix est de : <%= @amount %> €</span>
    </label>
  </article>  <br/>  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
  data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
  data-description="Achat d'un produit"
  data-amount=<%= @stripe_amount %>
  data-currency="eur"
  data-locale="auto"></script>
<% end %>

app/views/static_pages/index.html.erb
<ul>
  <% if user_signed_in? %>
    <li>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    </li>

    <li>
      Voici ton email : <%= current_user.email %>
    </li>

    <li>
      <%= link_to "Secret page", static_pages_secret_path %>
    </li>

    <li>
      <%= link_to "Edit email / password", edit_user_registration_path %>
    </li>

  <% else %>
    <li>    
      <%= link_to "Sign in", new_user_session_path %>
    </li>

    <li>
      <%= link_to "Sign up", new_user_registration_path %>
    </li>

  <% end %>
</ul>

app/views/static_pages/secret.html.erb
<div class="card mb-3" style="max-width: 540px; margin: 0 auto; float: none; margin-bottom: 10px; margin-top: 50px"> 
  <div class="row no-gutters">
    <div class="col-md-4">
     
    </div>
    <div class="col-md-8">
      <div class="card-body">
       
        <p class="card-text"><small class="text-muted">combien de event cree</small></p>
        <%= current_user.email %> <br/>
        <%= link_to "update", edit_user_path(current_user) %>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
    <br><br><br>
      <%= form_with model: @user, method: :patch, local: true do |form| %>
        
        <div class="form-group">
          <%= form.label :fisrt_name %><br>
          <%= form.text_field :fisrt_name, class: "form-control" %>
        </div>
        
        <div class="form-group">
          <%= form.label :last_name %><br>
          <%= form.text_field :last_name, class: "form-control"  %>
        </div>
        
        <div class="form-group">
          <%= form.label :description %><br>
          <%= form.text_field :description, class: "form-control"  %>
        </div>
      
        <input type="submit">

      <% end %>

      

    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="card mb-3" style="max-width: 540px; margin: 0 auto; float: none; margin-bottom: 10px; margin-top: 50px"> 
  <div class="row no-gutters">
    <div class="col-md-4">
      <%= form_tag user_avatars_path(@user), multipart: true do %>
        <%= file_field_tag :avatar %>
        <%= submit_tag "mettre à jour" %>
      <% end %>
    </div>
    <div class="col-md-8">
      <div class="card-body">

      

        <%= @user.fisrt_name %> 
        <%= @user.last_name %> <br/>
        <%= @user.description %>

          


        <p class="card-text"><small class="text-muted">combien de event cree</small></p>
      </div>
    </div>
  </div>
</div>
      

      <%= Event.find(@user.id) %>
      
      